import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

// TODO: Create Orders Page
// TODO: Create Checkout Page

// TODO: Menu Page
// TODO: Menu Layout
// TODO: Menu Item Deatails Component

// TODO: Finish Cart Logic

// TODO: Profile Page

// TODO: Share form states

// TODO: Demo Options prompt to browse all pages without backend

// TODO: Change Language

// TODO: Refactor

export const metadata: Metadata = {
  title: "ALBAIK | البيك",
  description: "Generated by create next app",
};

const navItems = [
  {
    label: "Story",
    href: "/#story",
  },
  {
    label: "Purpose",
    href: "/#purpose",
  },
  {
    label: "Menu",
    href: "/menu",
  },
];

const policyLinks = [
  {
    label: "Terms & Conditions",
    href: "terms",
  },
  {
    label: "Food Safety Policy",
    href: "safety",
  },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-background">
        <Header navItems={navItems} />
        {children}
        <Footer navItems={navItems} policyLinks={policyLinks} />
      </body>
    </html>
  );
}
